### This Notebook contains Numpy basics 

In [13]:
from datetime import datetime as dt
dt.now()

datetime.datetime(2019, 9, 10, 18, 6, 28, 248244)

In [15]:
import time as t
t.time()

1568119075.7249837

In [1]:
l=[5]

In [6]:
import sys
sys.getsizeof(l)

72

# Basics

In [2]:
import numpy as np

In [42]:
a=np.array([1,2,3,4])   #dtype can be int32 or int64

In [43]:
print(a)

[1 2 3 4]


In [41]:
b=np.array([[1,2],[3,4],[5,6]],dtype='int16')

In [17]:
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [44]:
a.ndim

1

In [19]:
b.ndim

2

In [45]:
a.shape

(4,)

In [46]:
a.itemsize

4

In [23]:
b.itemsize

2

In [47]:
a.size

4

In [40]:
c=np.array([[1,1],[1,1,1]])
c.nbytes

16

In [48]:
a.nbytes

16

In [32]:
b.nbytes

12

In [33]:
type(a)

numpy.ndarray

# accessing specific elements, rows, col etc.

In [56]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [53]:
a[1,5]

13

In [58]:
print(a[1,:])

[ 8  9 10 11 12 13 14]


In [61]:
a[:,::2]

array([[ 1,  3,  5,  7],
       [ 8, 10, 12, 14]])

In [65]:
a[:,1::2]

array([[ 2,  4,  6],
       [ 9, 11, 13]])

### 3D array

In [66]:
a=np.array([[[1,2],[1,4]],[[2,2],[2,4]]])

In [68]:
a.ndim
a.shape

(2, 2, 2)

# Intiliazing diff types of array

In [70]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [72]:
a=np.ones((2,3),dtype='int16')
a

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [81]:
a=np.random.rand(3,3)
a

array([[0.87776524, 0.60187705, 0.17000458],
       [0.60667661, 0.56323226, 0.8192187 ],
       [0.61184526, 0.64162721, 0.90814772]])

In [93]:
#for integers
a=np.random.randint(1,6,size=(3,3))
a

array([[4, 4, 1],
       [5, 1, 2],
       [2, 3, 4]])

In [97]:
# identity matrix
a=np.identity(3,dtype='int16')

In [98]:
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [107]:
a=np.array([[1,2,3]])

In [110]:
b=np.repeat(a,3)

In [111]:
print(b)

[1 1 1 2 2 2 3 3 3]


# Basic Mathematics

### arange()

In [7]:
import numpy as np
a=np.arange(0,9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
a.reshape(9)[::4]

array([0, 4, 8])

In [10]:
type(lambda x:x+1)

function

In [85]:
"the dry"[4:7]

'dry'

In [1]:
['A','C']+[1,2]

['A', 'C', 1, 2]